networks:
  borsibaar-network:
    driver: bridge

services:
  backend:
    container_name: backend
    depends_on:
      postgres:
        condition: service_started
    environment:
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    expose:
    - '8080'
    image: vanemarendaja-borsibaar-tiim_28-backend
    networks:
      borsibaar-network: {}
    ports:
    - 127.0.0.1:8080:8080/tcp
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    environment:
      BACKEND_URL: http://backend:8080
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    expose:
    - '3000'
    image: vanemarendaja-borsibaar-tiim_28-frontend
    networks:
      borsibaar-network: {}
    ports:
    - 127.0.0.1:3000:3000/tcp
    restart: unless-stopped

  nginx:
    container_name: nginx
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    image: nginx:alpine
    networks:
      borsibaar-network: {}
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    profiles:
    - do-not-start
    restart: unless-stopped
    volumes:
    - /home/ubuntu/borsibaar/nginx/conf.d:/etc/nginx/conf.d:ro
    - /home/ubuntu/borsibaar/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /home/ubuntu/borsibaar/nginx/ssl:/etc/nginx/ssl:ro

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:17
    networks:
      borsibaar-network: {}
    ports:
    - published: 5432
      target: 5432
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw
version: '3.3'
volumes:
  postgres_data: {}
